// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCorcskb_q431HJd1yXi7sWXo-irh4cw5g',
    appId: '1:708677665190:web:f50d2bdfd903364d57cf67',
    messagingSenderId: '708677665190',
    projectId: 'todo-app-8087b',
    authDomain: 'todo-app-8087b.firebaseapp.com',
    storageBucket: 'todo-app-8087b.appspot.com',
    measurementId: 'G-W7VFPVJHFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl1t8Soscy_Q53NSXkvfo12SzXORZwdqU',
    appId: '1:708677665190:android:ca982e1f0738db8457cf67',
    messagingSenderId: '708677665190',
    projectId: 'todo-app-8087b',
    storageBucket: 'todo-app-8087b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGT4rRnbbebJmWepKgwksSDNI38xFntVc',
    appId: '1:708677665190:ios:b2ba9fc85bd805f657cf67',
    messagingSenderId: '708677665190',
    projectId: 'todo-app-8087b',
    storageBucket: 'todo-app-8087b.appspot.com',
    iosBundleId: 'com.example.todoAppRoute',
  );
}
